{
    "name": "MRP Shopfloor",
    "version": "19.0.0.1.0",
    "category": "Manufacturing",
    "summary": "Meta module for the Shopfloor and gateway V0.1 stack",
    "license": "LGPL-3",
    "author": "OpenAI",
    "depends": [
        "mrp_shopfloor_core",
        "mrp_gateway_core",
        "mrp_gateway_runtime",
        "mrp_gateway_adapter_http",
        "mrp_gateway_adapter_mqtt",
        "mrp_gateway_adapter_modbus",
        "mrp_gateway_adapter_ads",
        "mrp_gateway_adapter_opcua",
        "mrp_gateway_adapter_s7",
        "mrp_shopfloor_execution",
        "mrp_shopfloor_frontend",
        "mrp_shopfloor_audit",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
