{
    "name": "MRP Gateway Adapter OPC UA",
    "version": "19.0.0.1.0",
    "category": "Manufacturing/Configuration",
    "author": "OpenAI",
    "summary": "OPC UA adapter baseline for gateway runtime diagnostics and node mapping",
    "license": "LGPL-3",
    "depends": ["base", "mrp", "mrp_gateway_runtime", "mrp_gateway_core"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "views/opcua_actions.xml",
        "views/opcua_menus.xml",
        "views/opcua_adapter_views.xml",
        "views/opcua_node_views.xml",
        "views/opcua_diagnostic_views.xml",
    ],
    "application": False,
    "installable": True,
}
