{
    "name": "MRP Gateway Runtime",
    "version": "19.0.0.1.0",
    "category": "Manufacturing/Configuration",
    "author": "OpenAI",
    "summary": "Runtime events, heartbeat ingestion, and command processing for gateway integrations",
    "license": "LGPL-3",
    "depends": ["base", "mrp", "mrp_gateway_core", "mrp_shopfloor_core"],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ir_cron.xml",
        "views/gateway_runtime_diagnostic_views.xml",
        "views/gateway_runtime_issue_views.xml",
        "views/gateway_runtime_issue_actions.xml",
        "views/gateway_runtime_probe_views.xml",
        "views/gateway_runtime_actions.xml",
        "views/gateway_runtime_menus.xml",
        "views/gateway_runtime_adapter_views.xml",
        "views/gateway_runtime_heartbeat_views.xml",
        "views/gateway_runtime_event_views.xml",
    ],
    "application": False,
    "installable": True,
}
